# Generated by Django 3.2.8 on 2021-12-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzas',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('pizzas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.pizzas')),
            ],
        ),
    ]
